### ISSUE TITLE
Male+Female: Add additional identifier

### ISSUE THREAD

**Issue by p24-max** [teambank/ratenkaufbyeasycredit-lib-php#2]
Magento2 One-Step-Checkout (FireCheckout) uses ENUMs for male=1 and female=2. So that easyCredit module gets compatible with firecheckout one-step-checkout, please add those magic numbers here:
https://github.com/teambank/ratenkaufbyeasycredit-lib-php/blob/9715e472471fd7ed9dd8089f88f0e118109f57b7/src/Client.php#L6-L7

```
    protected $_customerPrefixMalePatterns = array('Herr','Mr','male','männlich', '1');
    protected $_customerPrefixFemalePatterns = array('Frau','Ms','Miss','Mrs','female','weiblich', '2');
```

**Comment by netzkollektiv** [comment]
This library is deprecated and not being used in recent versions of the easyCredit plugins.
