### ISSUE TITLE
Incompatible with Magento 2.4.6

### ISSUE THREAD

**Issue by MTheProgrammer** [teambank/ratenkaufbyeasycredit-lib-php#3]
Hello,

in Magento 2.4.6 many Zend_ classes has been removed, among which is Zend_Http_Client.

This class uses Zend_Http_Client and fails on the most recent installation:
https://github.com/teambank/ratenkaufbyeasycredit-lib-php/blob/9715e472471fd7ed9dd8089f88f0e118109f57b7/src/Client/HttpClientFactory.php

Magento suggests to use \Laminas\Http\Client as replacement for Zend_Http_Client.
Unfortunatelly, `laminas/laminas-http` is for >= PHP 8 only.

Here is my forked repo and branch:
https://github.com/MTheProgrammer/ratenkaufbyeasycredit-lib-php/tree/feature/magento-2-4-6-compat

If you would like to keep your library backward compatible then it is necessary to create another version for Magento 2.4.6+

**Comment by netzkollektiv** [comment]
Thank you! This library is deprecated and not being used in recent versions of the easyCredit plugins.
